apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics
