apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    serviceMonitorSelector: prometheus
spec:
  endpoints:
    - interval: 60s
      port: metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: kube-state-metrics

