---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        env:
        - name: DATA_SOURCE_USER
          value: postgres_exporter
        - name: DATA_SOURCE_PASS
          value: beholder
        - name: DATA_SOURCE_URI
          value: "postgres.grafana-infra.svc.cluster.local:5432/grafana?sslmode=disable"
        ports:
        - containerPort: 9187
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
      name: metrics
