# This is a basic workflow to help you get started with Actions

name: Fake post to Elasticsearch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: List changed JSON files in the last commit
        id: changed_json_files
        run: |
          # Get the list of .json files changed in the last commit
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '.json$' || true)
          echo "Changed JSON files: $changed_files"

      # Runs a set of commands using the runners shell
      - name: Fake post
        run: |
          for f in ${{ steps.changed_json_files.outputs.files }}; do
            echo "curl $f"
          done
